version: "3.8"

services:
  docling-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
